name: Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: k8s-amd64
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build and push the pr-scoped prod target
        uses: mattjmorrison-homelab/actions-k8s@bcd046d4581cc4ffce4de813396f81420ce32e30 # main
        with:
          service-account: docker-backstage-job
          image: gcr.io/kaniko-project/executor@sha256:4e7a52dd1f14872430652bb3b027405b8dfd17c4538751c620ac005741ef9698
          shell: "false"
          command: >-
            --context=git://github.com/mattjmorrison-homelab/docker-backstage.git#refs/heads/${{ github.head_ref }}
            --dockerfile=Dockerfile --skip-unused-stages=true --target=prod
            --destination=registry.morrisons.site/docker-backstage:pr-${{ github.event.pull_request.head.sha }}-prod
          secret-volume: docker-backstage-zot-pull-secret:/kaniko/.docker
          active-deadline-seconds: "1800"

      - name: Build and push the pr-scoped test target
        uses: mattjmorrison-homelab/actions-k8s@bcd046d4581cc4ffce4de813396f81420ce32e30 # main
        with:
          service-account: docker-backstage-job
          image: gcr.io/kaniko-project/executor@sha256:4e7a52dd1f14872430652bb3b027405b8dfd17c4538751c620ac005741ef9698
          shell: "false"
          command: >-
            --context=git://github.com/mattjmorrison-homelab/docker-backstage.git#refs/heads/${{ github.head_ref }}
            --dockerfile=Dockerfile --skip-unused-stages=true --target=test
            --destination=registry.morrisons.site/docker-backstage:pr-${{ github.event.pull_request.head.sha }}-test
          secret-volume: docker-backstage-zot-pull-secret:/kaniko/.docker
          active-deadline-seconds: "1800"
