name: Publish

on:
  pull_request:
    types: [closed]

jobs:
  promote:
    if: github.event.pull_request.merged == true
    runs-on: k8s-amd64
    steps:
      - name: Promote the PR's already-built prod image to the deployed tag
        uses: mattjmorrison-homelab/actions-k8s@bcd046d4581cc4ffce4de813396f81420ce32e30 # main
        with:
          service-account: docker-backstage-job
          image: gcr.io/go-containerregistry/crane@sha256:1f968817b95790bed063f71175aa6b8ff879fa17064020415f3e18bb6e6a36e1
          shell: "false"
          command: >-
            tag registry.morrisons.site/docker-backstage:pr-${{ github.event.pull_request.head.sha }}-prod
            prod
          env: DOCKER_CONFIG=/kaniko/.docker
          secret-volume: docker-backstage-zot-pull-secret:/kaniko/.docker
          active-deadline-seconds: "120"

      - name: Promote the PR's already-built test image to the deployed tag
        uses: mattjmorrison-homelab/actions-k8s@bcd046d4581cc4ffce4de813396f81420ce32e30 # main
        with:
          service-account: docker-backstage-job
          image: gcr.io/go-containerregistry/crane@sha256:1f968817b95790bed063f71175aa6b8ff879fa17064020415f3e18bb6e6a36e1
          shell: "false"
          command: >-
            tag registry.morrisons.site/docker-backstage:pr-${{ github.event.pull_request.head.sha }}-test
            test
          env: DOCKER_CONFIG=/kaniko/.docker
          secret-volume: docker-backstage-zot-pull-secret:/kaniko/.docker
          active-deadline-seconds: "120"
